=== InstruktoriBrno/routing-system/boxes/game_logic/data/round_schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "properties": {
        "roundId": {
            "type": "integer"
        },
        "roundName": {
            "type": "string"
        },
        "duration": {
            "type": "integer"
        },
        "routers": {
            "type": "object",
            "additionalProperties": {
                "type": "object",
                "description": "Default assignment of pipaky to Router labels. Any pipak can assume any Label (for redundancy purposes). These values are defaults, so we don't need to update each of them manually pre-game.",
                "properties": {
                    "mac": {
                        "type": "string",
                        "description": "MAC address of the router that should assume this logical address"
                    }
                }
            }
        },
        "links": {
            "type": "array",
            "description": "List of all links in the network. The links are bi-directional. Only one of the directions is listed here.",
            "items": [
                {
                    "type": "string",
                    "description": "String of exactly two Router label chars."
                }
            ]
        },
        "packets": {
            "type": "object",
            "additionalProperties": {
                "type": "object",
                "properties": {
                    "type": {
                        "enum": [
                            "standard",
                            "priority",
                            "hopper",
                            "visitall"
                        ]
                    },
                    "releaseTime": {
                        "type": "integer",
                        "description": "Gametime when this packet should be released. Not enforced, value is for itinerary generator tool"
                    },
                    "source": {
                        "type": "string"
                    },
                    "destination": {
                        "type": "string"
                    },
                    "points": {
                        "type": "integer"
                    },
                    "pointsPerMinuteLeft": {
                        "type": "integer"
                    },
                    "minutesToDeliver": {
                        "type": "integer"
                    },
                    "pointsPerHop": {
                        "type": "integer"
                    }
                },
                "required": [
                    "type",
                    "releaseTime",
                    "source"
                ],
                "additionalProperties": false
            }
        },
        "events": {
            "type": "array",
            "description": "Pre-planned network events that will happen during game",
            "items": [
                {
                    "type": "object",
                    "properties": {
                        "category": {
                            "enum": [
                                "linkDown"
                            ]
                        },
                        "relativeTimestamp": {
                            "type": "number",
                            "description": "When should the event take place, in seconds from game start"
                        }
                    },
                    "required": [
                        "category",
                        "relativeTimestamp"
                    ]
                }
            ]
        }
    },
    "required": [
        "roundId",
        "roundName",
        "duration",
        "routers",
        "links",
        "packets",
        "events"
    ],
    "additionalProperties": false
}

=== InstruktoriBrno/routing-system/boxes/game_logic/data/test_jun_24/round1.json
{
    "roundId": 2,
    "roundName": "Test: Round 1",
    "duration": 900,
    "routers": {
        "L": {
            "mac": "xx:xx:xx:xx:xx:xx"
        },
        "A": {
            "mac": "xx:xx:xx:xx:xx:xx"
        },
        "D": {
            "mac": "xx:xx:xx:xx:xx:xx"
        },
        "C": {
            "mac": "xx:xx:xx:xx:xx:xx"
        },
        "J": {
            "mac": "xx:xx:xx:xx:xx:xx"
        },
        "E": {
            "mac": "xx:xx:xx:xx:xx:xx"
        },
        "B": {
            "mac": "xx:xx:xx:xx:xx:xx"
        },
        "M": {
            "mac": "xx:xx:xx:xx:xx:xx"
        },
        "O": {
            "mac": "xx:xx:xx:xx:xx:xx"
        },
        "N": {
            "mac": "xx:xx:xx:xx:xx:xx"
        },
        "F": {
            "mac": "xx:xx:xx:xx:xx:xx"
        },
        "K": {
            "mac": "xx:xx:xx:xx:xx:xx"
        },
        "G": {
            "mac": "xx:xx:xx:xx:xx:xx"
        },
        "I": {
            "mac": "xx:xx:xx:xx:xx:xx"
        },
        "H": {
            "mac": "xx:xx:xx:xx:xx:xx"
        }
    },
    "links": [  "AD", "AL", "AM",
                "BE", "BI", "BL",
                "CD", "CJ", "CO",
                "DN",
                "EG", "EJ",
                "FJ", "FK", "FN",
                "GI", "GK",
                "HI", "HL", "HM",
                "JK",
                "MO",
                "NO"],
    "packets": {
        "000": {"type": "standard", "releaseTime":60, "source": "A", "destination": "C", "points": 10},
        "050": {"type": "priority", "releaseTime":120, "source": "A", "destination": "C", "pointsPerMinuteLeft": 4, "minutesToDeliver": 5},
        "080": {"type": "hopper", "releaseTime":180, "source": "A", "pointsPerHop": 1},
        "090": {"type": "visitall", "releaseTime":210, "source": "A", "points": 50}
    },
    "events": [
    ]
}

=== InstruktoriBrno/routing-system/boxes/game_logic/data/test_jun_24/round2.json
{
    "roundId": 3,
    "roundName": "Test: Round 2",
    "duration": 900,
    "routers": {
        "E": {
            "mac": "xx:xx:xx:xx:xx:xx"
        },
        "H": {
            "mac": "xx:xx:xx:xx:xx:xx"
        },
        "G": {
            "mac": "xx:xx:xx:xx:xx:xx"
        },
        "I": {
            "mac": "xx:xx:xx:xx:xx:xx"
        },
        "M": {
            "mac": "xx:xx:xx:xx:xx:xx"
        },
        "A": {
            "mac": "xx:xx:xx:xx:xx:xx"
        },
        "D": {
            "mac": "xx:xx:xx:xx:xx:xx"
        },
        "F": {
            "mac": "xx:xx:xx:xx:xx:xx"
        },
        "K": {
            "mac": "xx:xx:xx:xx:xx:xx"
        },
        "J": {
            "mac": "xx:xx:xx:xx:xx:xx"
        },
        "L": {
            "mac": "xx:xx:xx:xx:xx:xx"
        },
        "N": {
            "mac": "xx:xx:xx:xx:xx:xx"
        },
        "O": {
            "mac": "xx:xx:xx:xx:xx:xx"
        },
        "B": {
            "mac": "xx:xx:xx:xx:xx:xx"
        },
        "C": {
            "mac": "xx:xx:xx:xx:xx:xx"
        }
    },
    "links": [  
        "AB", "AD", "AM", "AN", "AO",
        "BC", "BD", "BO",
        "CD", "DE", "EF",
        "DE",
        "EF", "EH",
        "FG", "FH", "FI", "FK",
        "GH", "GI", "GJ",
        "HI",
        "IJ", "IK", "IM",
        "JK", "JL",
        "KL",
        "LM", "LN",
        "MN", "MO",
        "NO"
    ],
    "packets": {
    },
    "events": [
    ]
}
